version: '2'
services:
  ln2xgrc-app:
    image: ln2xgrc
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATA_MONGODB_URI=mongodb://ln2xgrc-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=LN2XGRC
      - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
      - SPRING_DATA_JEST_URI=http://ln2xgrc-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://ln2xgrc-elasticsearch:9200
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    ports:
      - 8080:8080
  ln2xgrc-mongodb:
    extends:
      file: mongodb.yml
      service: ln2xgrc-mongodb
  ln2xgrc-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: ln2xgrc-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
