version: '2'
services:
  ln2xgrc-mongodb:
    image: mongo:4.0.9
    ports:
      - '27017:27017'
    command: mongos --configdb ln2xgrc-mongodb-config
  ln2xgrc-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  ln2xgrc-mongodb-config:
    image: mongo:4.0.9
    container_name: ln2xgrc-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
